[tool.poetry]
name = "anndata"
version = "0.7.1"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.3"
numpy = "^1.18.3"
scipy = "^1.4.1"
h5py = "^2.10.0"
natsort = "^7.0.1"
packaging = "^20.3"
objgraph = "^3.4.1"
setuptools_scm = "^4.1.2"
pytoml = "^0.1.21"

[tool.poetry.dev-dependencies]
loompy = ">=3.0.5"
pytest = ">=3.9"
pytest-cov = "^2.8.1"
codacy-coverage = "^1.3.11"
zarr = "^2.4.0"
sklearn = "^0.0"
xlrd = "^1.2.0"
joblib = "^0.14.1"
black = "^19.10b0"
boltons = "^20.1.0"
pytest-xdist = "^1.31.0"
ipykernel = "^5.2.1"
pympler = "^0.8"
matplotlib = "^3.2.1"
memory_profiler = "^0.57.0"
pylint = "^2.5.3"
mypy = "^0.782"
pydocstyle = "^5.0.2"

[tool.pytest.ini_options]
addopts = '--doctest-modules'
python_files = 'test_*.py'
testpaths = ['anndata', 'docs/concatenation.rst']
xfail_strict = true

[tool.black]
line-length = 88
target-version = ['py36']
exclude = '^/build/.*$'
